security:
    firewalls:
        api:
            pattern: ^/api/
            stateless: true
            jwt: ~
        main:
            anonymous: true
    access_control:
        - { path: ^/api, roles: ROLE_USER }
